```{r}
#| label: basetabfuncmed
#| cache: true
#| cache.comments: false

basetabfuncmed_inner <- function(x, data, stratavar, catdig, contdig) {
  tmp <- data %>%
    filter(!is.na(!!sym(x)) & !is.na(!!sym(stratavar)))

  cl <- class(data %>% pull(!!sym(x)))
  if (cl %in% c("character", "factor")) {
    out <- tmp %>%
      group_by(!!sym(stratavar), .drop = F) %>%
      count(!!sym(x), .drop = F) %>%
      mutate(
        out = paste0(n, " (", fn(n / sum(n) * 100, catdig), ")"),
        out = case_when(
          sum(n) == 0 ~ "-",
          n < 10 ~ "<10",
          TRUE ~ out
        ),
        level = !!sym(x)
      ) %>%
      ungroup() %>%
      select(!!sym(stratavar), out, level) %>%
      pivot_wider(names_from = !!sym(stratavar), values_from = out)

    # stand diff
    check <- tmp %>%
      count(!!sym(stratavar), !!sym(x))
    levs <- out %>% pull(level)
    nlevs <- length(levs)
    if (nrow(check) >= 4) {
      if (nlevs == 2) {
        p <- fn(stddiff.binary(tmp, stratavar, x)[1, "stddiff"], 2)
      }
      if (nlevs > 2) {
        p <- fn(stddiff.category(tmp, stratavar, x)[1, "stddiff"], 2)
      }
      p2 <- fn(chisq.test(tmp %>% pull(!!sym(stratavar)), tmp %>% pull(!!sym(x)))$p.value, p = T, dig = 3)
    } else {
      p <- "-"
      p2 <- "-"
    }

    # if levels No, Yes only present Yes
    if (nlevs == 2 & all(levs %in% c("No", "Yes"))) {
      out <- out %>%
        filter(level == "Yes") %>%
        mutate(
          var = x,
          p = p,
          p2 = p2,
          level = NA
        )
    } else {
      out <- out %>%
        mutate(
          var = NA,
          p = NA,
          p2 = NA
        )
      out <- out %>% add_row(
        var = x,
        p = p,
        p2 = p2,
        .before = 1
      )
    }
  } else if (cl %in% c("numeric", "integer")) {
    if (length(contdig) > 1) {
      if (any(contdig$vars %in% x)) {
        contdig <- contdig %>%
          filter(vars == x) %>%
          pull(contdig)
      } else {
        contdig <- 0
      }
    }
    out <- tmp %>%
      group_by(!!sym(stratavar), .drop = F) %>%
      reframe(
        med = quantile(!!sym(x), na.rm = T, probs = c(0.5)),
        q1 = quantile(!!sym(x), na.rm = T, probs = c(0.25)),
        q3 = quantile(!!sym(x), na.rm = T, probs = c(0.75)),
        n = n()
      ) %>%
      mutate(
        out = paste0(fn(med, contdig), " [", fn(q1, contdig), "-", fn(q3, contdig), "]"),
        out = case_when(
          n == 0 ~ "-",
          n < 10 ~ "<10",
          TRUE ~ out
        )
      ) %>%
      ungroup() %>%
      select(!!sym(stratavar), out) %>%
      pivot_wider(names_from = !!sym(stratavar), values_from = out)

    # stand diff
    check <- tmp %>%
      count(!!sym(stratavar), !is.na(!!sym(x)))
    if (nrow(check) >= 2) {
      tmp <- tmp %>%
        mutate(rankx = rank(!!sym(x)))
      p <- fn(stddiff.numeric(tmp, stratavar, "rankx")[1, "stddiff"], 2)
      p2 <- fn(kruskal.test(formula(paste0(x, " ~ ", stratavar)), data = tmp)$p.value, p = T, dig = 3)
    } else {
      p <- "-"
      p2 <- "-"
    }

    out <- out %>%
      mutate(
        var = x,
        p = p,
        p2 = p2
      )
  } else {
    stop("Unknown class in baseline table")
  }
}

contdig <- 0
catdig <- 0

basetabfuncmed <- function(data, strata2, strataname, novars = NULL) {
  tab <- data %>%
    group_by(case) %>%
    count(!!sym(strata2), .drop = F) %>%
    mutate(n = paste0(n, " (", fn(n / sum(n) * 100, catdig), ")")) %>%
    ungroup() %>%
    pivot_wider(names_from = c(case, !!sym(strata2)), values_from = n) %>%
    mutate(
      var = "N (%)",
      level = NA,
      p1 = NA,
      p12 = NA,
      p2 = NA,
      p22 = NA
    ) %>%
    select(var, level, Comparator_No, Comparator_Yes, p1, p12, ANOCA_No, ANOCA_Yes, p2, p22)

  levstrata <- levels(data %>% pull(case))
  tabvarstmp <- setdiff(tabvars, c(strata2, novars))
  tabtmp1 <- sapply(tabvarstmp,
    FUN = basetabfuncmed_inner, data = data %>% filter(case == levstrata[1]),
    stratavar = strata2, catdig = catdig, contdig = contdig
  )
  tabtmp2 <- sapply(tabvarstmp,
    FUN = basetabfuncmed_inner, data = data %>% filter(case == levstrata[2]),
    stratavar = strata2, catdig = catdig, contdig = contdig
  )

  tabtmp1 <- bind_rows(tabtmp1)
  tabtmp2 <- bind_rows(tabtmp2)
  tabtmp <- bind_cols(tabtmp1, tabtmp2 %>% select(-var, -level)) %>%
    select(var, level, everything())
  names(tabtmp) <- names(tab)
  tab <- bind_rows(tab, tabtmp)

  tab <- tab %>%
    mutate(
      # if recoding or categorizing will still get org label
      var_tmp = str_replace_all(var, "(_cat2|_cat)", "")
    )

  tab <- left_join(tab,
    metavars %>%
      select(variable, label, unit),
    by = c("var_tmp" = "variable")
  ) %>%
    mutate(
      Variable = coalesce(label, var_tmp),
      Variable = if_else(!is.na(unit),
        paste0(Variable, " (", unit, ")"),
        Variable
      ),
      Variable = if_else(!is.na(level) & !is.na(Variable),
        paste0(Variable, " ", level),
        coalesce(Variable, paste0("  ", level))
      ),
      # small fixes
      Variable = str_replace_all(Variable, fixed("Disposable income (100 SEK)"), "Income")
    )

  cn <- c("Variable", rep(c(paste("No", strataname), strataname, "SD", "P-value"), 2))

  # excel
  tab <- tab %>%
    select(Variable, Comparator_No:p22)

  make_one_xlsxsheet(tab, colnames = cn)

  tab <- tab %>%
    mutate(
      # so no probs
      Variable = sanitize_text(Variable),
      Variable = str_replace_all(Variable, fixed("²"), "\\textsuperscript{2}"),
      Variable = str_replace_all(Variable, fixed("$>$="), "$\\geq$"),
      Variable = str_replace_all(Variable, fixed("$<$="), "$\\leq$")
    )

  indent_rows <- tab %>%
    mutate(
      indent_rows = str_detect(Variable, "  "),
      rows = row_number()
    ) %>%
    filter(indent_rows) %>%
    pull(rows)

  cn <- sanitize_text(cn)

  default_kable(tab,
    font_size = 7.5,
    longtable = TRUE,
    escape = FALSE,
    col.names = cn
  ) %>%
    add_indent(indent_rows) %>%
    add_header_above(c(" " = 1, "Comparator" = 4, "ANOCA" = 4)) %>%
    footnote(
      footnote_order = c("general", "symbol", "alphabet"),
      general_title = "",
      general = c(
        "Categorical variables are presented with n (%) and continuous variables with median [q1-q3]."
      ),
      threeparttable = T
    )
}
```

```{r}
#| label: tbl-base-rasiarni
#| cache: true
#| cache.comments: false
#| dependson: basetabfuncmed
#| tbl-cap: "Baseline characteristics - RASi/ARNi"
#| tbl-pos: "H"

basetabfuncmed(data = sdata, strata2 = "sos_lm_rasiarni", strataname = "RASi/ARNi")
```

```{r}
#| label: tbl-base-lipidlow
#| cache: true
#| cache.comments: false
#| dependson: basetabfuncmed
#| tbl-cap: "Baseline characteristics - Lipid lowering"
#| tbl-pos: "H"

basetabfuncmed(data = sdata, strata2 = "sos_lm_antikoagulantia", strataname = "Lipid lowering")
```

```{r}
#| label: tbl-base-bbl
#| cache: true
#| cache.comments: false
#| dependson: basetabfuncmed
#| tbl-cap: "Baseline characteristics - Beta-blockers"
#| tbl-pos: "H"

basetabfuncmed(data = sdata, strata2 = "sos_lm_bbl", strataname = "Beta-blockers")
```

```{r}
#| label: tbl-base-ccb
#| cache: true
#| cache.comments: false
#| dependson: basetabfuncmed
#| tbl-cap: "Baseline characteristics - Calcium channel blockers"
#| tbl-pos: "H"

basetabfuncmed(data = sdata, strata2 = "sos_lm_ccb", strataname = "Calcium channel blockers")
```
