```{r}
#| label: predictorsfunccc
#| cache: true
#| cache.comments: false

predictorsfunccc <- function(time, event, xbreaks, novar = NULL, stratavar = NULL) {
  coxvars <- setdiff(modvars_case, novar)
  coxvars[coxvars %in% stratavar] <- paste0("strata(", coxvars[coxvars %in% stratavar], ")")

  mod <- summary(coxph(formula(paste0(
    "Surv(", time, ",", event, " == 'Yes') ~ ", paste(coxvars, collapse = " + ")
  )), data = sdata))

  out <- tibble(
    var = rownames(mod$coefficients),
    hr = mod$conf.int[, "exp(coef)"],
    lci = mod$conf.int[, "lower .95"],
    uci = mod$conf.int[, "upper .95"]
  ) %>%
    mutate(
      hrprint = paste0(
        fn(hr, dig = 2),
        " (", fn(lci, dig = 2),
        "-", fn(uci, dig = 2), ")"
      ),
      var = str_remove_all(var, fixed("Yes"))
    )

  out <- left_join(out,
    metavars %>%
      select(variable, label),
    by = c("var" = "variable")
  ) %>%
    mutate(
      var = coalesce(label, var),
      var = case_when(
        var == "year_cat2011-2015" ~ "Year 2011-2015 vs 2006-2010",
        var == "year_cat2016-2019" ~ "Year 2016-2019 vs 2006-2010",
        var == "scb_sexFemale" ~ "Female vs Male",
        var == "scb_age_cat60-75" ~ "Age (years) 60-75 vs <60",
        var == "scb_age_cat>75" ~ "Age (years) >75 vs <60",
        var == "scb_educationUniversity" ~ "University vs Compulsory school",
        var == "scb_educationSecondary school" ~ "Secondary vs Compulsory school",
        var == "scb_dispincome_cat2nd tertile within year" ~ "Income 2nd vs 1st tertile",
        var == "scb_dispincome_cat3rd tertile within year" ~ "Income 3rd vs 1st tertile",
        var == "scaar_smokePrevious" ~ "Previous vs Non-smoker",
        var == "scaar_smokeCurrent" ~ "Current vs Non-smoker",
        var == "scaar_bmi_cat>=30" ~ "BMI (kg/m²) >=30 vs <30",
        var == "scaar_css>=2" ~ "CSS 2-4 vs 1",
        var == "scb_maritalstatusSingle/widowed/divorced" ~ "Single vs Married",
        var == "Malignant cancer within 3 years" ~ "Malignant cancer",
        var == "scaar_stenos30-49" ~ "Stenos (%) 30-49 vs 0-29",
        TRUE ~ var
      ),
      var = str_replace_all(var, ">=", "\u2265"),
      var = str_replace_all(var, "<=", "\u2264")
    ) %>%
    arrange(hr) %>%
    mutate(
      var = forcats::fct_inorder(var)
    ) %>%
    select(-label)

  out$` ` <- paste(rep(" ", nrow(out)), collapse = " ")

  colnames(out)[1] <- "  "
  colnames(out)[5] <- "HR (95% CI)"

  tm <- forest_theme(
    core = list(bg_params = list(fill = c("#F0F0F0", "white"))),
    base_size = 14,
    refline_gp = gpar(lty = "solid"),
    ci_col = global_cols[1],
    ci_lwd = 2.5,
    arrow_length = 0.08
    # xaxis_ticks_gp = gpar(fontface = "bold"),
    # arrow_gp = gpar(fontface = "bold")
  ) # ,
  # Table cell padding, width 4 and heights 3
  # core = list(padding = unit(c(4, 3), "mm")))

  # Draw the forest plot with rearranged columns
  p <- forest(out[, c(1, 6, 5)],
    est = out$hr,
    lower = out$lci,
    upper = out$uci,
    ci_column = 2,
    sizes = 1.25,
    # nudge_y = 0.35,
    x_trans = "log",
    arrow_lab = c("Better", "Worse"),
    xlim = c(min(xbreaks), max(xbreaks)),
    ticks_at = xbreaks,
    theme = tm
  )

  create_pptx(p, width = 8, height = 8, forestp = T)
  p
}
```

```{r}
#| label: fig-predictors-comp-compcase
#| cache: true
#| cache.comments: false
#| dependson: predictorsfunccc
#| fig-cap: "Association between baseline characteristics and the composite outcome - Complete case analyses"
#| fig-width: 8
#| fig-height: 8

predictorsfunccc(
  time = outvars$time[1],
  event = outvars$var[1],
  xbreaks = c(0.3, 1, 3, 7)
)
```

```{r}
#| label: fig-predictors-revasc-compcase
#| cache: true
#| cache.comments: false
#| dependson: predictorsfunccc
#| fig-cap: "Association between baseline characteristics and revascularzation - Complete case analyses"
#| fig-width: 8
#| fig-height: 8

predictorsfunccc(
  time = outvars$time[6],
  event = outvars$var[6],
  xbreaks = c(0.2, 0.5, 1, 2, 4),
  novar = "scaar_stenos"
)
```
