```{r}
#| label: splinefunc
#| cache: true
#| cache.comments: false

splinefunc <- function(time, event, eventname, ylims = c(0.1, 0.2, 0.5, 1, 2, 3)) {
  fitcrude <- cph(formula(paste0("Surv(", time, ",", event, "== 'Yes') ~ rcs(year, 5)")),
    data = sdatauseforimp
  )
  fitadj <- fit.mult.impute(
    (formula(paste(
      "Surv(", time, ",", event, "== 'Yes') ~ rcs(year, 5) + ",
      paste(coxvars, collapse = " + ")
    ))),
    fitter = cph,
    xtrans = impsdata, data = sdatauseforimp, pr = F
  )

  plotcrude <- Predict(fitcrude, year, ref.zero = TRUE, fun = exp)
  plotadj <- Predict(fitadj, year, ref.zero = TRUE, fun = exp)

  plotspline <- tibble(bind_rows(
    plotcrude %>%
      mutate(typemod = 1),
    plotadj %>%
      mutate(typemod = 2) %>%
      select(year, yhat, lower, upper, typemod)
  )) %>%
    mutate(typemod = factor(typemod, levels = 1:2, labels = c("Crude", "Adjusted")))

  size_use <- 18
  med <- quantile(sdatauseforimp %>% pull(year), na.rm = T, p = 0.5)

  p <- ggplot(plotspline, aes(x = year, y = yhat, colour = typemod)) +
    geom_hline(yintercept = 1, linetype = "longdash", ) +
    geom_vline(xintercept = med, linetype = "longdash") +
    geom_line(linewidth = 1.5) +
    geom_ribbon(data = plotspline %>% filter(typemod == "Crude"), aes(ymin = lower, ymax = upper), alpha = 0.2, linetype = 0, fill = global_cols[1], show.legend = FALSE) +
    geom_ribbon(data = plotspline %>% filter(typemod == "Adjusted"), aes(ymin = lower, ymax = upper), alpha = 0.2, linetype = 0, fill = global_cols[2], show.legend = FALSE) +
    scale_color_manual(values = global_cols[1:2]) +
    theme_classic() +
    theme(
      plot.margin = margin(0, 0, 0, 0, "cm"), # TRouBLe
      text = element_text(size = size_use, face = "bold"),
      legend.position = "bottom",
      legend.title = element_blank(),
      axis.text = element_text(color = "black")
    ) +
    scale_y_continuous(
      trans = "log", breaks = ylims,
      limits = c(min(ylims), max(ylims))
      # expand = c(0, 0),
    ) +
    scale_x_continuous(
      breaks = seq(2006, 2020, 1), guide = guide_axis(n.dodge = 2) # expand = c(0, 0)
    ) +
    labs(x = "Calender year", y = "Hazard Ratio (95% CI)")

  create_pptx(p)
  p
}
```

```{r}
#| label: fig-spline
#| cache: true
#| cache.comments: false
#| dependson: splinefunc
#| fig-cap: "Association between outcomes and time for cases (HR = 1 at median calender year)"
#| fig-subcap: !expr outvars$shortname
#| layout-ncol: 2
#| layout-nrow: 2

coxvars <- setdiff(modvars_case, "year_cat")
coxvars[coxvars %in% stratavars_case] <- paste0("strata(", coxvars[modvars_case %in% stratavars_case], ")")

dd <- datadist(sdatauseforimp)
options(datadist = "dd")

nr <- 1
splinefunc(
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr]
)
nr <- 2
splinefunc(
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr]
)
nr <- 3
splinefunc(
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr]
)
nr <- 4
splinefunc(
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  ylims = c(0.1, 0.2, 0.5, 1, 2, 3, 5)
)
nr <- 5
splinefunc(
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr]
)
nr <- 6
splinefunc(
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr],
  ylims = c(0.01, 0.05, 0.1, 0.2, 0.5, 1, 2, 4, 8)
)
nr <- 7
splinefunc(
  time = outvars$time[nr],
  event = outvars$var[nr],
  eventname = outvars$shortname[nr]
)
```
